import { Talent, Skill, Review } from "@/types";

export const mockSkills: Skill[] = [
  { id: "1", name: "Cuisine africaine", category: "cuisine", level: "expert", yearsExperience: 5, verified: true },
  { id: "2", name: "Développement Web", category: "tech", level: "expert", yearsExperience: 3, verified: true },
  { id: "3", name: "Couture", category: "couture", level: "expert", yearsExperience: 8, verified: true },
  { id: "4", name: "Électricité", category: "bricolage", level: "intermediate", yearsExperience: 4, verified: false },
  { id: "5", name: "Photographie", category: "photographie", level: "expert", yearsExperience: 6, verified: true },
  { id: "6", name: "Plomberie", category: "bricolage", level: "expert", yearsExperience: 10, verified: true },
  { id: "7", name: "Design graphique", category: "tech", level: "intermediate", yearsExperience: 2, verified: false },
  { id: "8", name: "Coiffure", category: "coiffure", level: "expert", yearsExperience: 7, verified: true },
  { id: "9", name: "Menuiserie", category: "artisanat", level: "expert", yearsExperience: 12, verified: true },
  { id: "10", name: "Pâtisserie", category: "cuisine", level: "intermediate", yearsExperience: 3, verified: true },
];

export const mockTalents: Talent[] = [
  {
    id: "1",
    name: "Amina Koné",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop",
    bio: "Passionnée de cuisine depuis mon enfance, je partage les saveurs de l'Afrique de l'Ouest avec amour et authenticité.",
    skills: [mockSkills[0], mockSkills[9]],
    location: { city: "Abidjan", country: "Côte d'Ivoire" },
    rating: 4.9,
    reviewCount: 127,
    verified: true,
    portfolio: [
      { id: "p1", type: "image", url: "https://images.unsplash.com/photo-1604909052743-94e838986d24?w=800", title: "Plat traditionnel ivoirien" },
      { id: "p2", type: "image", url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800", title: "Attiéké poisson" },
    ],
    joinedDate: "2023-05-12",
    userType: "talent",
  },
  {
    id: "2",
    name: "Kofi Mensah",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    bio: "Développeur autodidacte, j'ai appris le code en ligne et je construis des sites web modernes pour les PME africaines.",
    skills: [mockSkills[1], mockSkills[6]],
    location: { city: "Accra", country: "Ghana" },
    rating: 4.8,
    reviewCount: 89,
    verified: true,
    portfolio: [
      { id: "p3", type: "image", url: "https://images.unsplash.com/photo-1547658719-da2b51169166?w=800", title: "Application e-commerce" },
      { id: "p4", type: "image", url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800", title: "Dashboard analytics" },
    ],
    joinedDate: "2023-03-20",
    userType: "talent",
  },
  {
    id: "3",
    name: "Fatoumata Diallo",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop",
    bio: "Couturière de renom, je crée des pièces uniques inspirées des tissus africains traditionnels avec une touche moderne.",
    skills: [mockSkills[2]],
    location: { city: "Dakar", country: "Sénégal" },
    rating: 5.0,
    reviewCount: 203,
    verified: true,
    portfolio: [
      { id: "p5", type: "image", url: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800", title: "Collection Wax 2024" },
      { id: "p6", type: "image", url: "https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=800", title: "Robe de soirée" },
    ],
    joinedDate: "2022-11-08",
    userType: "talent",
  },
  {
    id: "4",
    name: "Jean-Pierre Kamga",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
    bio: "Électricien expérimenté, j'interviens pour tous vos travaux d'installation et de dépannage électrique.",
    skills: [mockSkills[3]],
    location: { city: "Yaoundé", country: "Cameroun" },
    rating: 4.7,
    reviewCount: 156,
    verified: true,
    portfolio: [
      { id: "p7", type: "image", url: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800", title: "Installation résidentielle" },
    ],
    joinedDate: "2023-01-15",
    userType: "talent",
  },
  {
    id: "5",
    name: "Aïcha Touré",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop",
    bio: "Photographe passionnée, je capture les moments précieux et l'essence de la vie africaine.",
    skills: [mockSkills[4]],
    location: { city: "Bamako", country: "Mali" },
    rating: 4.9,
    reviewCount: 98,
    verified: true,
    portfolio: [
      { id: "p8", type: "image", url: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800", title: "Portrait artistique" },
      { id: "p9", type: "image", url: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800", title: "Mariage traditionnel" },
    ],
    joinedDate: "2023-07-22",
    userType: "talent",
  },
  {
    id: "6",
    name: "Ibrahim Ndiaye",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop",
    bio: "Plombier professionnel avec 10 ans d'expérience. Interventions rapides et travail soigné garanti.",
    skills: [mockSkills[5]],
    location: { city: "Dakar", country: "Sénégal" },
    rating: 4.8,
    reviewCount: 142,
    verified: true,
    portfolio: [],
    joinedDate: "2022-09-10",
    userType: "talent",
  },
  {
    id: "7",
    name: "Mariam Keita",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop",
    bio: "Coiffeuse spécialisée dans les coiffures afro et les tresses. Je sublime votre beauté naturelle.",
    skills: [mockSkills[7]],
    location: { city: "Ouagadougou", country: "Burkina Faso" },
    rating: 5.0,
    reviewCount: 187,
    verified: true,
    portfolio: [
      { id: "p10", type: "image", url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800", title: "Tresses box braids" },
      { id: "p11", type: "image", url: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800", title: "Coiffure afro naturelle" },
    ],
    joinedDate: "2023-02-18",
    userType: "talent",
  },
  {
    id: "8",
    name: "Samuel Owusu",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=400&fit=crop",
    bio: "Menuisier artisan, je fabrique des meubles sur mesure en bois massif avec un savoir-faire traditionnel.",
    skills: [mockSkills[8]],
    location: { city: "Kumasi", country: "Ghana" },
    rating: 4.9,
    reviewCount: 76,
    verified: true,
    portfolio: [
      { id: "p12", type: "image", url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800", title: "Table artisanale" },
      { id: "p13", type: "image", url: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800", title: "Bibliothèque sur mesure" },
    ],
    joinedDate: "2022-12-05",
    userType: "talent",
  },
  {
    id: "9",
    name: "Nadia Benali",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop",
    bio: "Pâtissière créative, je réalise des gâteaux personnalisés pour toutes vos occasions spéciales.",
    skills: [mockSkills[9]],
    location: { city: "Tunis", country: "Tunisie" },
    rating: 4.7,
    reviewCount: 94,
    verified: false,
    portfolio: [
      { id: "p14", type: "image", url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800", title: "Gâteau de mariage" },
      { id: "p15", type: "image", url: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800", title: "Cupcakes personnalisés" },
    ],
    joinedDate: "2023-06-30",
    userType: "talent",
  },
  {
    id: "10",
    name: "Youssouf Traoré",
    avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=400&fit=crop",
    bio: "Mécanicien automobile autodidacte, je répare et entretiens tous types de véhicules avec passion.",
    skills: [{ id: "11", name: "Mécanique auto", category: "mecanique", level: "expert", yearsExperience: 8, verified: true }],
    location: { city: "Bobo-Dioulasso", country: "Burkina Faso" },
    rating: 4.6,
    reviewCount: 112,
    verified: true,
    portfolio: [],
    joinedDate: "2023-04-12",
    userType: "talent",
  },
  {
    id: "11",
    name: "Zalika Mwangi",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop",
    bio: "Artiste peintre, je crée des œuvres inspirées de la culture africaine contemporaine.",
    skills: [{ id: "12", name: "Peinture", category: "artisanat", level: "expert", yearsExperience: 6, verified: true }],
    location: { city: "Nairobi", country: "Kenya" },
    rating: 4.9,
    reviewCount: 68,
    verified: true,
    portfolio: [
      { id: "p16", type: "image", url: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800", title: "Art africain moderne" },
      { id: "p17", type: "image", url: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=800", title: "Portrait contemporain" },
    ],
    joinedDate: "2023-08-05",
    userType: "talent",
  },
  {
    id: "12",
    name: "Omar Fofana",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop",
    bio: "Jardinier paysagiste, je transforme vos espaces extérieurs en véritables oasis de verdure.",
    skills: [{ id: "13", name: "Jardinage", category: "autre", level: "intermediate", yearsExperience: 5, verified: false }],
    location: { city: "Conakry", country: "Guinée" },
    rating: 4.5,
    reviewCount: 53,
    verified: false,
    portfolio: [
      { id: "p18", type: "image", url: "https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800", title: "Jardin tropical" },
    ],
    joinedDate: "2023-09-14",
    userType: "talent",
  },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    fromUserId: "u1",
    fromUserName: "Moussa Diaby",
    fromUserAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100",
    rating: 5,
    comment: "Excellent travail ! Très professionnelle et ponctuelle. Je recommande vivement.",
    date: "2024-01-15",
  },
  {
    id: "r2",
    fromUserId: "u2",
    fromUserName: "Sarah Mensah",
    fromUserAvatar: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=100",
    rating: 5,
    comment: "Une vraie artiste ! Le résultat dépasse mes attentes.",
    date: "2024-01-10",
  },
  {
    id: "r3",
    fromUserId: "u3",
    fromUserName: "Abdoul Kader",
    fromUserAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100",
    rating: 4,
    comment: "Très bon service, juste un petit retard mais le travail est impeccable.",
    date: "2024-01-08",
  },
];

export const skillCategories = [
  { id: "cuisine", name: "Cuisine", count: 45 },
  { id: "tech", name: "Tech", count: 38 },
  { id: "artisanat", name: "Artisanat", count: 52 },
  { id: "bricolage", name: "Bricolage", count: 67 },
  { id: "mecanique", name: "Mécanique", count: 29 },
  { id: "photographie", name: "Photographie", count: 34 },
  { id: "couture", name: "Couture", count: 41 },
  { id: "coiffure", name: "Coiffure", count: 56 },
  { id: "education", name: "Éducation", count: 23 },
  { id: "autre", name: "Autre", count: 18 },
];

export const cities = [
  "Abidjan",
  "Accra",
  "Dakar",
  "Yaoundé",
  "Bamako",
  "Ouagadougou",
  "Kumasi",
  "Tunis",
  "Bobo-Dioulasso",
  "Nairobi",
  "Conakry",
  "Lagos",
  "Kinshasa",
  "Douala",
];
